name: "sandbox"
profile: "default"

config-version: 2

# metadata: 
#   metabase-collection: 'dbt_queris'
model-paths: ["models"]
seed-paths: ["seeds"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
  - "logs"

models:
  sandbox:
    materialized: table
    staging:
      materialized: view
