FROM eclipse-temurin:11-jre

ARG MB_VERSION
ARG CURL_FLAGS

RUN curl -O ${CURL_FLAGS} https://downloads.metabase.com/v${MB_VERSION}/metabase.jar

EXPOSE 3000

ENTRYPOINT ["java", "-jar", "metabase.jar"]
