version: 2

models:
  - name: birds
    description: Birds.
    columns:
      - name: id
        description: Bird identifier.

      - name: name
        description: Bird name.

      - name: create_ts
        description: Create timestamp.
