-- Databricks initialization script
-- Create schema and skus table in the configured catalog
CREATE SCHEMA IF NOT EXISTS ${DATABRICKS_CATALOG}.${DATABRICKS_SCHEMA};
DROP TABLE IF EXISTS ${DATABRICKS_CATALOG}.${DATABRICKS_SCHEMA}.skus;
CREATE TABLE ${DATABRICKS_CATALOG}.${DATABRICKS_SCHEMA}.skus (
  SKU_ID INT NOT NULL,
  PRODUCT STRING NOT NULL
) USING DELTA;
INSERT INTO ${DATABRICKS_CATALOG}.${DATABRICKS_SCHEMA}.skus (SKU_ID, PRODUCT)
VALUES (1, 'jaffle');
-- Add table comment to help with metadata
COMMENT ON TABLE ${DATABRICKS_CATALOG}.${DATABRICKS_SCHEMA}.skus IS 'SKU inventory table for dbt-metabase testing';
COMMENT ON COLUMN ${DATABRICKS_CATALOG}.${DATABRICKS_SCHEMA}.skus.SKU_ID IS 'Primary key for SKU';