name: Main

on:
  pull_request:
    branches:
      - master
  release:
    types: [created]

jobs:
  build:
    name: Build and validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Requirements
        run: make requirements

      - name: Build
        run: make build

      - name: Lint check
        run: make lint

      - name: Type check
        run: make type

      - name: Test
        run: make test

      - name: Publish a Python distribution to PyPI
        if: github.event_name == 'release'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
