name: master

on:
  push:
    branches:
      - master
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.6.x"

      - name: Requirements
        run: make requirements

      - name: Build
        run: make build

      - name: Formatting check (black)
        run: make check-fmt

      - name: Imports ordering check (isort)
        run: make check-imports

      - name: Lint Python check (pylint)
        run: make check-lint-python

      - name: Type check (mypy)
        run: make check-type

      - name: Test
        run: make test

      - name: Publish a Python distribution to PyPI
        if: github.event_name == 'release'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
