version: 2

sources:
  - name: inventory
    tables:
      - name: skus

models:
  - name: stg_customers
    meta:
      metabase.visibility_type: hidden
    columns:
      - name: customer_id
        data_tests:
          - unique
          - not_null
      - name: first_name
      - name: last_name

  - name: stg_orders
    columns:
      - name: order_id
        data_tests:
          - unique
          - not_null
      - name: status
        data_tests:
          - accepted_values:
              values: ["placed", "shipped", "completed", "return_pending", "returned"]
      - name: order_date
      - name: customer_id
      - name: sku_id
        data_tests:
          - not_null
          - relationships:
              to: source('inventory', 'skus')
              field: sku_id

  - name: stg_payments
    columns:
      - name: payment_id
        data_tests:
          - unique
          - not_null
      - name: payment_method
        data_tests:
          - accepted_values:
              values: ["credit_card", "coupon", "bank_transfer", "gift_card"]
      - name: order_id
      - name: amount
